#
# (C) COPYRIGHT 2013 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#


# The parent Mali Kbuild adds this object to mali_kbase-y with its full
# platform/qogirn6pro path. Do not add it to obj-y here: this file is included
# from the parent directory, where a relative obj-y path resolves incorrectly.
