# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_SPRD) += \
	ums9230-4h10-overlay.dtbo

ums9230-4h10-overlay.dtbo-base := ums9230.dtb


always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
