# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-$(CONFIG_ZTE_POWER_SUPPLY_DEBUG) := -DDEBUG

zte_power_supply-$(CONFIG_ZTE_POWER_SUPPLY_COMMON) += zte_power_supply_core.o zte_power_supply_sysfs.o
obj-$(CONFIG_ZTE_POWER_SUPPLY) += zte_power_supply.o

